auth/create-post-signup&post-login
HuijinKang/food-order-management-service pull request #12
Opened 2024-11-11 14:15 UTC by rua0704

## #️⃣ 연관된 이슈
#1 

## 📝 작업 내용
- 회원가입 API 개발
- 로그인 API 개발
- 테스트 코드 작성

**실수로 signup과 login을 merge를 해서 2개가 합쳐졌습니다.**

### 📸 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

2024-11-12 02:28 UTC, HuijinKang commented
LGTM(look good to me)

2024-11-12 02:34 UTC, HuijinKang approved these changes
LGTM(look good to me)

2024-11-12 03:15 UTC, Soeng-dev requested changes
전반적으로 좋은데, 댓글단부분 논의가 필요해 보입니다.

2024-11-12 03:15 UTC, Soeng-dev commented on src/main/java/org/sparta/foodordermanagementservice/common/exeption/GlobalExceptionHandler.java
에러메시지 잘 보여줘서 좋아요

2024-11-12 03:15 UTC, Soeng-dev commented on src/main/java/org/sparta/foodordermanagementservice/entity/Timestamped.java
created_by, named_by도 자동으로 auth에서 받아와서 가능한거같아서 해보겠습니다. 지금까지 작업물 정리해서 pr올린뒤 시작해볼게요

2024-11-12 03:15 UTC, Soeng-dev commented on src/main/java/org/sparta/foodordermanagementservice/dto/request/LoginRequestDTO.java
dto들에 @NoArgsConstructor가 붙어있는데, 꼭 필요한 상황이 없다면 인스턴스 데이터 유효성이 깨질것같습니다.
필드가 비어있는체로 돌아다니는걸 방지하는게 좋을 것 같아요

2024-11-12 03:15 UTC, Soeng-dev commented on src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
entity와 dto간의 맵핑이 repository레이어에서 하는게 더 적절해 보입니다. 
table의 수정으로 인한 코드수정이 service레이어가 아닌 repository레이어에서 하는게  레이어별 역할에 맞는 설계라고 생각합니다.

2024-11-12 03:18 UTC, rua0704 commented on src/main/java/org/sparta/foodordermanagementservice/entity/Timestamped.java
강현님이 하신다고 하셔서 임시로 작업해둔 것이였습니다.

2024-11-12 03:25 UTC, rua0704 commented on src/main/java/org/sparta/foodordermanagementservice/dto/request/LoginRequestDTO.java
습관적으로 붙였네요. 수정하겠습니다

2024-11-12 05:42 UTC, pkhyun commented
LGTM 👍👍

2024-11-12 05:55 UTC, pkhyun approved these changes

2024-11-13 01:45 UTC, rua0704 commented on src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
entity와 dto 맵핑은 repository 레이어에서 하지 않는 것으로 알고 있습니다.
![image](https://github.com/user-attachments/assets/6dd64de1-6ee2-4de7-a94a-e3588e1ddf2a)

2024-11-13 01:55 UTC, merged