user/create-get-user
HuijinKang/food-order-management-service pull request #15
Opened 2024-11-12 09:25 UTC by rua0704

## #️⃣ 연관된 이슈
# 13
> ex) #이슈번호, #이슈번호

## 📝 작업 내용
유저 조회 API 구현
테스트 코드 작성
@Secured 설정
에러 핸들러 추가

### 📸 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-11-12 11:32 UTC, Soeng-dev requested changes
수고하셨습니다~

2024-11-12 11:32 UTC, Soeng-dev commented on src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
> +    @Override
마찬가지로 dto 변환시 각 계층에 해당하는곳에서 맵핑해줘야 할것같습니다.

2024-11-12 11:36 UTC, rua0704 commented on src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
> +    @Override
예시를 들어 설명해주시겠어요

2024-11-13 03:22 UTC, HuijinKang reviewed
고생하셨습니다.

2024-11-13 05:00 UTC, merged